/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.BadConsequence;
import NapakalakiGame.NumericBadConsequence;
import NapakalakiGame.SpecificBadConsequence;

/**
 *
 * @author danibolanos & jomabose
 */
public class PendingBadConsequenceView extends javax.swing.JPanel {
    
    BadConsequence badConsequenceModel;

    /**
     * Creates new form BadConsequenceView
     */
    public PendingBadConsequenceView() {
        initComponents();
          // setVisibleSpecific(false);
          // setVisibleNumeric(false);
    }
    
    public void setPendingBadConsequence(BadConsequence bc){
       badConsequenceModel = bc;
       
       if(badConsequenceModel instanceof NumericBadConsequence){
           //setVisibleNumeric(true);
          // setVisibleSpecific(false);
          this.randomVT.setText(Integer.toString(((NumericBadConsequence)badConsequenceModel).getNVisibleTreasures()));
          this.randomHT.setText(Integer.toString(((NumericBadConsequence)badConsequenceModel).getNHiddenTreasures()));
       }
       
       if(badConsequenceModel instanceof SpecificBadConsequence){
           //setVisibleNumeric(false);
           //setVisibleSpecific(true);
          this.specificVT.setText(((SpecificBadConsequence)badConsequenceModel).getSpecificVisibleTreasures().toString());
          this.specificHT.setText(((SpecificBadConsequence)badConsequenceModel).getSpecificHiddenTreasures().toString());
       }
       
       repaint();
    }
    
    public void setVisibleNumeric(boolean set){
        nLabel1.setVisible(set);
        nLabel2.setVisible(set);
        nLabel3.setVisible(set);
        randomHT.setVisible(set);
        randomVT.setVisible(set);
    }
    
    public void setVisibleSpecific(boolean set){
        sLabel1.setVisible(set);
        sLabel2.setVisible(set);
        sLabel3.setVisible(set);
        specificHT.setVisible(set);
        specificVT.setVisible(set);
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nLabel1 = new javax.swing.JLabel();
        sLabel1 = new javax.swing.JLabel();
        nLabel2 = new javax.swing.JLabel();
        sLabel2 = new javax.swing.JLabel();
        nLabel3 = new javax.swing.JLabel();
        sLabel3 = new javax.swing.JLabel();
        randomVT = new javax.swing.JLabel();
        specificVT = new javax.swing.JLabel();
        randomHT = new javax.swing.JLabel();
        specificHT = new javax.swing.JLabel();

        nLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        nLabel1.setText("Tesoros Visibles a descartar:");

        sLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        sLabel1.setText("Tesoros Ocultos a descartar:");

        nLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        nLabel2.setText("Aleatorios:");

        sLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        sLabel2.setText("Aleatorios:");

        nLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        nLabel3.setText("Específicos:");

        sLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        sLabel3.setText("Específicos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(randomVT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(randomHT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sLabel3))
                            .addComponent(sLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(specificVT, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                            .addComponent(specificHT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(specificVT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nLabel2)
                        .addComponent(randomVT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(randomHT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(sLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(specificHT, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nLabel1;
    private javax.swing.JLabel nLabel2;
    private javax.swing.JLabel nLabel3;
    private javax.swing.JLabel randomHT;
    private javax.swing.JLabel randomVT;
    private javax.swing.JLabel sLabel1;
    private javax.swing.JLabel sLabel2;
    private javax.swing.JLabel sLabel3;
    private javax.swing.JLabel specificHT;
    private javax.swing.JLabel specificVT;
    // End of variables declaration//GEN-END:variables
}
